---
- name: 'include OS family specific variables'
  include_vars: '{{ ansible_os_family }}.yml'
  tags: 'sitecopy'

- import_tasks: 'validate.yml'
  tags: 'sitecopy'

- import_tasks: 'packages.yml'
  when: sitecopy__packages_manage
  tags: 'sitecopy'

- import_tasks: 'config.yml'
  tags: 'sitecopy'
