---
- name: 'OS family specific variables - ensure included'
  tags: 'sitecopy'
  include_vars: '{{ ansible_os_family }}.yml'

- name: 'packages tasks - ensure imported'
  tags: ['sitecopy', 'online']
  import_tasks: 'packages.yml'
  when: sitecopy__packages_manage

- name: 'config tasks - ensure imported'
  tags: 'sitecopy'
  import_tasks: 'config.yml'
