---
- name: "main variables - ensure validated"
  assert:
    that:
      - "{{ item.result }}"
    quiet: "{{ sitecopy__quiet }}"
  loop:
    - result: "{{ sitecopy__users | type_debug == 'list' }}"
      description: "sitecopy__users is list"
      value: "{{ sitecopy__users | type_debug }}"
    - result: "{{ sitecopy__packages_manage is boolean }}"
      description: "sitecopy__packages_manage is boolean"
      value: "{{ sitecopy__packages_manage }}"
  loop_control:
    label: "{{ item.description }}"
  tags: sitecopy

- name: "user existence - ensure checked"
  getent:
    database: passwd
    key: "{{ item.user }}"
  loop: "{{ sitecopy__users }}"
  loop_control:
    label: "sitecopy__users: {{ item.user }}"
  tags: sitecopy

- name: "OS family specific variables - ensure included"
  include_vars: "{{ ansible_os_family }}.yml"
  tags: sitecopy

- import_tasks: install.yml
  when: sitecopy__packages_manage
  tags: sitecopy, online

- import_tasks: config.yml
  tags: sitecopy
