---
- name: Prepare
  hosts: all
  become: True
  vars:
    ansible_python_interpreter: /usr/bin/python
  tasks:
    - name: "needed packages - ensure installed"
      package:
        state: present
        name:
          - python3
      when: "ansible_os_family == 'Suse'"
